import { ClassListData } from "./types";

export const TempClassList: ClassListData = [
  {
    id: 0,
    instructor: "김세영",
    title: "강의1",
    capacity: 10,
    applicants: 0,
    sellingPrice: 100000,
  },
  {
    id: 1,
    instructor: "김세영",
    title: "강의2",
    capacity: 10,
    applicants: 0,
    sellingPrice: 100000,
  },
  {
    id: 2,
    instructor: "김세영",
    title: "강의3",
    capacity: 10,
    applicants: 0,
    sellingPrice: 100000,
  },
  {
    id: 3,
    instructor: "김세영",
    title: "강의4",
    capacity: 10,
    applicants: 0,
    sellingPrice: 100000,
  },
  {
    id: 4,
    instructor: "김세영",
    title: "강의5",
    capacity: 10,
    applicants: 0,
    sellingPrice: 100000,
  },
  {
    id: 5,
    instructor: "김세영",
    title: "강의6",
    capacity: 10,
    applicants: 0,
    sellingPrice: 100000,
  },
  {
    id: 6,
    instructor: "김세영",
    title: "강의7",
    capacity: 10,
    applicants: 0,
    sellingPrice: 100000,
  },
  {
    id: 7,
    instructor: "김세영",
    title: "강의8",
    capacity: 10,
    applicants: 0,
    sellingPrice: 100000,
  },
  {
    id: 8,
    instructor: "김세영",
    title: "강의9",
    capacity: 10,
    applicants: 0,
    sellingPrice: 100000,
  },
];
